config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  resources :events do
    collection do
      get 'my_events'
      get 'booked_events'
    end

    member do
      post 'book_ticket'
    end
  end

  # Defines the root path route ("/")
  root "events#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
  has_many :tickets, dependent: :destroy

  validates :name, :description, :location, :date, :time, :total_tickets, presence: true
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, :join_table => :users_roles
  
  belongs_to :resource,
             :polymorphic => true,
             :optional => true
  

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/ticket.rb
class Ticket < ApplicationRecord
  belongs_to :user
  belongs_to :event
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :events, dependent: :destroy
  has_many :tickets, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :check_session_timeout

  private

  def check_session_timeout
    if session[:last_activity_time] && session_expired?
      reset_session
      flash[:alert] = "Your session has timed out. Please log in again."
      redirect_to new_user_session_path
    else
      session[:last_activity_time] = Time.current
    end
  end

  def session_expired?
    # Adjust the session timeout duration as needed.
    # debugger
    session_timeout_duration = 2.hours.to_i
    Time.current > (Time.zone.parse(session[:last_activity_time].to_s) + session_timeout_duration)
  end
end

app/controllers/concerns/events_concern.rb
module EventsConcern
  # to show only those events which are created by current user
  def my_events
    user = User.find_by(id: params[:user_id])
    @events = user.events
  end

  # to show those events for which current user has booked tickets
  def booked_events
    user = User.find_by(id: params[:user_id])
    events_ids = user.tickets.pluck(:event_id).uniq
    @events = Event.where(id: events_ids)
  end

  # to check if there are tickets available for a particular event
  def tickets_are_available?(ticket, event)
    ticket_count = ticket.quantity.to_i
    booked_tickets = event.booked_tickets.to_i
    total_tickets = event.total_tickets.to_i
    (total_tickets - (ticket_count + booked_tickets)) >= 0 ? true : false
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  include EventsConcern
  before_action :set_event, only: [:show, :edit, :update, :destroy, :book_ticket]

  def index
    @events = Rails.cache.fetch('all_events', expires_in: 5.minutes) do
      Event.all
    end
  end

  def show; end

  def new
    @event = Event.new
  end

  def edit; end

  def update
    if @event.update(event_params)
      flash[:notice] = "Event updated successfully"
      redirect_to @event
    else
      flash.now[:alert] = "Failed to update event"
      render :edit
    end
  end

  def create
    @event = Event.new(event_params)
    if @event.save
      flash[:notice] = "Event created successfully"
      redirect_to my_events_events_path(user_id: current_user.id)
    else
      flash.now[:alert] = "Failed to create event"
      render :new
    end
  end

  def destroy
    @event.destroy
    flash[:notice] = "Event deleted successfully"
    redirect_to events_path
  end

  # to book the ticket for an event
  def book_ticket
    ticket = Ticket.new(ticket_params)
    if tickets_are_available?(ticket, @event)
      save_ticket_and_update_event(ticket)
      flash[:notice] = "Tickets booked successfully"
    else
      flash.now[:alert] = "Failed to book tickets"
    end
    redirect_to event_path(@event.id)
  end

  private

  def save_ticket_and_update_event(ticket)
    ticket.save
    @event.update(booked_tickets: @event.booked_tickets.to_i + ticket.quantity.to_i)
  end
  
  def event_params
    params.require(:event).permit(:name, :description, :location, :date, :time, :total_tickets, :booked_tickets, :user_id)
  end

  def ticket_params
    params.permit(:quantity, :user_id, :event_id)
  end

  def set_event
    @event = Event.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
  def user_booked_tickets(event)
    quantity_array = current_user.tickets.where(event_id: event.id).pluck(:quantity)
    quantity_array.sum
  end

  def tickets_are_available?(event)
    (event.total_tickets - event.booked_tickets) > 0
  end

  def available_tickets_for_event(event)
    event.total_tickets - event.booked_tickets
  end

  def convert_time(time)
    time.present? ? Time.parse(time).strftime("%I:%M %p") : 'N/A'
  end

  def format_date(date)
    date.present? ? Time.parse(date.to_s).strftime("%d %B, %Y") : 'N/A'
  end
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/booked_events.html.erb
<p>
  <%= link_to 'All Events', events_path %> |
  <%= link_to 'My Events', my_events_events_path(user_id: current_user.id) %> |
  <%= link_to 'New Event', new_event_path %>
</p>
<h3 class="text-center"> My Booked Events </h3>
<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Date</th>
      <th>Time</th>
      <th>Total Tickets</th>
      <th>Booked Tickets</th>
      <th>Available Tickets</th>
      <th>Your Booked Tickets</th>
    </tr>
  </thead>
  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= link_to "#{event.name}", event_path(event.id) %></td>
        <td><%= format_date(event.date) %></td>
        <td><%= convert_time(event.time) %></td>
        <td><%= (event.total_tickets || 'N/A') %></td>
        <td><%= (event.booked_tickets || 'N/A') %></td>
        <td><%= available_tickets_for_event(event) %>
        <td><%= user_booked_tickets(event) %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/events/edit.html.erb
<p>
  <%= link_to 'All Events', events_path %> |
  <%= link_to 'My Events', my_events_events_path(user_id: current_user.id) %>
</p>

<h3>Edit Event</h3>

<%= form_with(model: @event, local: true, html: { class: "form" }) do |form| %>
  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: "form-control", placeholder: "Enter event name", required: true %>
  </div>

  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_area :description, class: "form-control", placeholder: "Enter event description", required: true %>
  </div>

  <div class="form-group">
    <%= form.label :location %>
    <%= form.text_area :location, class: "form-control", placeholder: "Enter event location", required: true %>
  </div>

  <div class="form-group">
    <%= form.label :date %>
    <%= form.date_field :date, class: "form-control", placeholder: "Select event date", required: true %>
  </div>

  <div class="form-group">
    <%= form.label :time %>
    <%= form.time_field :time, class: "form-control", placeholder: "Select event time", required: true %>
  </div>

  <div class="form-group">
    <%= form.label :total_tickets %>
    <%= form.number_field :total_tickets, class: "form-control", placeholder: "Enter available tickets count", required: true, min: @event.booked_tickets %>
  </div>

  <%= form.hidden_field :booked_tickets, value: (@event.booked_tickets || 0) %>
  <%= form.hidden_field :user_id, value: current_user.id %>

  <div class="form-group">
    <%= form.submit "Update Event", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/events/index.html.erb
<h1> Welcome to event management system </h1>
<hr>
<p>
  <%= link_to 'My Events', my_events_events_path(user_id: current_user.id) %> |
  <%= link_to 'My Booked Events', booked_events_events_path(user_id: current_user.id) %> |
  <%= link_to 'New Event', new_event_path %>
</p>
<h3 class="text-center"> All Events </h3>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Date</th>
      <th>Time</th>
      <th>Total Tickets</th>
      <th>Booked Tickets</th>
      <th>Available Tickets</th>
    </tr>
  </thead>
  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= link_to "#{event.name}", event_path(event.id) %></td>
        <td><%= format_date(event.date) %></td>
        <td><%= convert_time(event.time) %></td>
        <td><%= (event.total_tickets || 'N/A') %></td>
        <td><%= (event.booked_tickets || 'N/A') %></td>
        <td><%= available_tickets_for_event(event) %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/events/my_events.html.erb
<p>
  <%= link_to 'All Events', events_path %> |
  <%= link_to 'My Booked Events', booked_events_events_path(user_id: current_user.id) %> |
  <%= link_to 'New Event', new_event_path %>
</p>
<h3 class="text-center"> My Events </h3>
<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Date</th>
      <th>Time</th>
      <th>Total Tickets</th>
      <th>Booked Tickets</th>
      <th>Available Tickets</th>
    </tr>
  </thead>
  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= link_to "#{event.name}", event_path(event.id) %></td>
        <td><%= format_date(event.date) %></td>
        <td><%= convert_time(event.time) %></td>
        <td><%= (event.total_tickets || 'N/A') %></td>
        <td><%= (event.booked_tickets || 'N/A') %></td>
        <td><%= available_tickets_for_event(event) %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/events/new.html.erb
<p>
  <%= link_to 'All Events', events_path %> |
  <%= link_to 'My Events', my_events_events_path(user_id: current_user.id) %>
</p>

<h3>New Event</h3>

<%= form_with(model: @event, local: true, html: { class: "form" }) do |form| %>
  <div class="form-group mt-2">
    <%= form.label :name %>
    <%= form.text_field :name, class: "form-control", placeholder: "Enter event name", required: true %>
  </div>

  <div class="form-group mt-2">
    <%= form.label :description %>
    <%= form.text_area :description, class: "form-control", placeholder: "Enter event description", required: true %>
  </div>

  <div class="form-group mt-2">
    <%= form.label :location %>
    <%= form.text_area :location, class: "form-control", placeholder: "Enter event location", required: true %>
  </div>

  <div class="form-group mt-2">
    <%= form.label :date %>
    <%= form.date_field :date, class: "form-control", placeholder: "Select event date", required: true %>
  </div>

  <div class="form-group mt-2">
    <%= form.label :time %>
    <%= form.time_field :time, class: "form-control", placeholder: "Select event time", required: true %>
  </div>

  <div class="form-group mt-2">
    <%= form.label :total_tickets %>
    <%= form.number_field :total_tickets, class: "form-control", placeholder: "Enter available tickets count", required: true, min: 1, value: 1 %>
  </div>

  <%= form.hidden_field :booked_tickets, value: 0 %>

  <%= form.hidden_field :user_id, value: current_user.id %>

  <div class="form-group">
    <%= form.submit "Create Event", class: "btn btn-primary mt-3" %>
  </div>

<% end %>

app/views/events/show.html.erb
<p>
  <%= link_to 'All Events', events_path %> |
  <%= link_to 'My Events', my_events_events_path(user_id: current_user.id) %> |
  <%= link_to 'My Booked Events', booked_events_events_path(user_id: current_user.id) %>
</p>

<div class="show">
  <h3><%= @event.name %></h3>
  <div class="row">
    <div class="col-md-6">
      <p><strong>Description:</strong> <%= @event.description %></p>
      <p><strong>Location:</strong> <%= @event.location %></p>
      <p><strong>Date:</strong> <%= format_date(@event.date) %></p>
      <p><strong>Time:</strong> <%= convert_time(@event.time) %></p>
      <p><strong>Total Tickets:</strong> <%= @event.total_tickets %></p>
      <p><strong>Booked Tickets:</strong> <%= @event.booked_tickets %></p>
      <p><strong>Available Tickets:</strong> <%= available_tickets_for_event(@event) %></p>
      <p><strong>Created By:</strong> <%= @event.user.email %></p>
      <% if @event.user_id == current_user.id %>
        <p>
          <%= link_to 'Edit Event', edit_event_path(@event.id) %> |
          <%= link_to 'Delete', event_path(@event), data: { turbo_method: :delete,turbo_confirm: 'Are you sure?' } %>
        <p>
      <% end %>
    </div>
  </div>

  <hr>

  <h3>Book Ticket</h3>
  <% if tickets_are_available?(@event) %>
    <%= form_with(url: book_ticket_event_path(@event), method: :post) do |form| %>
      <div class="form-group">
        <%= form.label :quantity %>
        <%= form.number_field :quantity, class: "form-control", style: 'width: 200px;', min: 1, max: available_tickets_for_event(@event), value: 1 %>
      </div>

      <%= form.hidden_field :event_id, value: @event.id %>
      <%= form.hidden_field :user_id, value: current_user.id %>

      <div class="form-group">
        <%= form.submit "Book", class: "btn btn-primary" %>
      </div>
    <% end %>
  <% else %>
    <p>Sorry No tickets available !</p>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EventManagement</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.bundle.min.js"></script>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="text-center mt-5">
      <% if current_user.present? %>
        <%= link_to 'Sign out', destroy_user_session_path, data: { turbo_method: :delete }, class: 'btn btn-danger text-center' %>
      <% end %>
      <hr>
    </div>  
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name), class: "btn btn-lg btn-primary btn-block rounded-0 shadow" %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name), class: "btn btn-lg btn-primary btn-block rounded-0 shadow" %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>